[package]
name = "tn23-auth"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
axum = "0.8.5"
axum-extra = { version = "0.10.2", features = ["typed-header"] }
base64 = "0.22.1"
getrandom = { version = "0.3.3", features = ["std"] }
serde = { version = "1.0.228", features = ["derive"] }
tracing = "0.1.41"

[dev-dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
axum = "0.8.5"
dotenvy = "0.15.7"
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.47.1", features = ["full"] }
